/*
 * single_value_node.h
 *
 * 
 */

#ifndef _single_value_node_H_
#define _single_value_node_H_

#include <string.h>
#include "../external/cJSON.h"
#include "../include/list.h"
#include "../include/keyValuePair.h"
#include "../include/binary.h"

typedef struct single_value_node_t single_value_node_t;

#include "i_edm_type_reference.h"

// Enum KIND for single_value_node

typedef enum  { blockchainsservice_single_value_node_KIND_NULL = 0, blockchainsservice_single_value_node_KIND_None, blockchainsservice_single_value_node_KIND_Constant, blockchainsservice_single_value_node_KIND_Convert, blockchainsservice_single_value_node_KIND_NonResourceRangeVariableReference, blockchainsservice_single_value_node_KIND_BinaryOperator, blockchainsservice_single_value_node_KIND_UnaryOperator, blockchainsservice_single_value_node_KIND_SingleValuePropertyAccess, blockchainsservice_single_value_node_KIND_CollectionPropertyAccess, blockchainsservice_single_value_node_KIND_SingleValueFunctionCall, blockchainsservice_single_value_node_KIND_Any, blockchainsservice_single_value_node_KIND_CollectionNavigationNode, blockchainsservice_single_value_node_KIND_SingleNavigationNode, blockchainsservice_single_value_node_KIND_SingleValueOpenPropertyAccess, blockchainsservice_single_value_node_KIND_SingleResourceCast, blockchainsservice_single_value_node_KIND_All, blockchainsservice_single_value_node_KIND_CollectionResourceCast, blockchainsservice_single_value_node_KIND_ResourceRangeVariableReference, blockchainsservice_single_value_node_KIND_SingleResourceFunctionCall, blockchainsservice_single_value_node_KIND_CollectionFunctionCall, blockchainsservice_single_value_node_KIND_CollectionResourceFunctionCall, blockchainsservice_single_value_node_KIND_NamedFunctionParameter, blockchainsservice_single_value_node_KIND_ParameterAlias, blockchainsservice_single_value_node_KIND_EntitySet, blockchainsservice_single_value_node_KIND_KeyLookup, blockchainsservice_single_value_node_KIND_SearchTerm, blockchainsservice_single_value_node_KIND_CollectionOpenPropertyAccess, blockchainsservice_single_value_node_KIND_CollectionComplexNode, blockchainsservice_single_value_node_KIND_SingleComplexNode, blockchainsservice_single_value_node_KIND_Count, blockchainsservice_single_value_node_KIND_SingleValueCast, blockchainsservice_single_value_node_KIND_CollectionPropertyNode, blockchainsservice_single_value_node_KIND_AggregatedCollectionPropertyNode, blockchainsservice_single_value_node_KIND_In, blockchainsservice_single_value_node_KIND_CollectionConstant, blockchainsservice_single_value_node_KIND_RootPath, blockchainsservice_single_value_node_KIND_CustomQueryOption } blockchainsservice_single_value_node_KIND_e;

char* single_value_node_kind_ToString(blockchainsservice_single_value_node_KIND_e kind);

blockchainsservice_single_value_node_KIND_e single_value_node_kind_FromString(char* kind);



typedef struct single_value_node_t {
    struct i_edm_type_reference_t *type_reference; //model
    blockchainsservice_single_value_node_KIND_e kind; //enum

} single_value_node_t;

single_value_node_t *single_value_node_create(
    i_edm_type_reference_t *type_reference,
    blockchainsservice_single_value_node_KIND_e kind
);

void single_value_node_free(single_value_node_t *single_value_node);

single_value_node_t *single_value_node_parseFromJSON(cJSON *single_value_nodeJSON);

cJSON *single_value_node_convertToJSON(single_value_node_t *single_value_node);

#endif /* _single_value_node_H_ */

